
export const Path = {
    PUBLIC : '',
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    SERVICE: 'service', 
    PRIVATE: 'private', 
    PROFILE: 'profile', 
    DETAIL_POST: 'detail-post/:id', 
    BUY_SERVICE: 'buy-service/:id', 
    UPLOAD: 'upload',
    MANAGE_POST: 'manage-post',
    ADMIN: 'admin',
    SERVICE_MANAGE: 'services',
    POST_MANAGE: 'posts',
    DETAIL_POST_MANAGE: 'approve-post/:id',
    USER_MANAGE: 'users',
    THANK: 'thank',
  };